from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, Dict, List
from datetime import datetime
from enum import Enum

class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    ROTATE = "ROTATE"
    HOLD = "HOLD"

@dataclass
class MarketState:
    """Snapshot of market conditions at a point in time"""
    title: str
    count: int              # Current tweet count
    hours_left: float       # Hours until market closes
    daily_avg: float        # Historical daily average
    buckets: List[Dict]     # List of {bucket, min, max, ask, bid}
    timestamp: float
    metadata: Optional[Dict] = field(default=None)  # Optional: Additional market metadata (for event type detection)

@dataclass
class Signal:
    """Trading signal generated by strategy"""
    type: SignalType
    market_title: str
    bucket: str
    price: float
    confidence: float       # 0-1 confidence score
    reason: str
    metadata: Dict = None
    timestamp: float = None
    strategy_tag: str = "STANDARD"  # DNA Tag for position tracking

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now().timestamp()

@dataclass
class Position:
    """Current position in portfolio"""
    market: str
    bucket: str
    shares: float
    entry_price: float
    timestamp: float
    invested: float
    max_price_seen: float = None
    price_history: List[Dict] = None
    strategy_tag: str = "STANDARD"  # DNA Tag: STANDARD or MOONSHOT

    def __post_init__(self):
        if self.max_price_seen is None:
            self.max_price_seen = self.entry_price
        if self.price_history is None:
            self.price_history = []

class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Each strategy must implement:
    - analyze(): Generate trading signals from market state
    - calculate_position_size(): Determine bet size for signals
    """

    def __init__(self, config: Dict):
        self.config = config
        self.name = self.__class__.__name__

    @abstractmethod
    def analyze(self, market_state: MarketState, current_positions: List[Position]) -> List[Signal]:
        """
        Analyze market state and generate trading signals.

        Args:
            market_state: Current market conditions
            current_positions: List of positions we currently hold in this market

        Returns:
            List of Signal objects (can be empty if no action)
        """
        pass

    @abstractmethod
    def calculate_position_size(
        self,
        signal: Signal,
        available_cash: float,
        portfolio_value: float
    ) -> float:
        """
        Calculate appropriate position size for a signal.

        Args:
            signal: The trading signal
            available_cash: Current cash balance
            portfolio_value: Total portfolio value

        Returns:
            Dollar amount to invest
        """
        pass

    def should_execute(self, signal: Signal) -> bool:
        """
        Determine if a signal should be executed.

        Default implementation checks confidence threshold.
        Override for custom logic.
        """
        min_confidence = self.config.get("min_confidence", 0.5)
        return signal.confidence >= min_confidence

    def validate_signal(self, signal: Signal, current_positions: List[Position]) -> tuple[bool, str]:
        """
        Validate signal against strategy rules.

        Returns:
            (is_valid, reason)
        """
        return True, "OK"

    def on_trade_executed(self, signal: Signal, execution_price: float, shares: float):
        """
        Hook called after trade is executed.
        Use for state updates, logging, etc.
        """
        pass

    def on_market_closed(self, market_title: str, final_count: int):
        """
        Hook called when a market closes.
        Use for cleanup, performance tracking, etc.
        """
        pass
